"Remove NERDTree Sidebar
set guioptions-=L

colorscheme base16-default
set guifont=Hack:h11

highlight EWOL ctermbg=red ctermfg=black guibg=#3B2B35 guifg=black
highlight tabsUse ctermbg=red ctermfg=black guibg=#203B23 guifg=black

function TabHighlight()
	call matchadd('EWOL', '\s\+$', 11)
	call matchadd('tabsUse', '\t\+', 12)
endfunction

nnoremap <Leader>" :call TabHighlight()<CR>
nnoremap <Leader>2 :call clearmatches()<CR>
