# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
    eval `/usr/libexec/path_helper -s`
fi

# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE="$mainfolder/_local/_zshhistfile"
HISTSIZE=1000
SAVEHIST=1000

# End of lines configured by zsh-newuser-install

# Base16 Shell
#export BASE16=1
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
# Executes $PROMPT_COMMAND before every prompt
#  - used to change the name of tmux windows/panes
# precmd() { eval "$PROMPT_COMMAND" }

unsetopt nomatch

source "$mainfolder/zsh/zsh_keymaps"

# .zshrc
autoload -U promptinit && promptinit
prompt pure

source "$mainfolder/source/exports"
export KEYTIMEOUT=1
# bindkey -v

PROMPT='%(?.%F{magenta}.%F{red})${${KEYMAP/vicmd/❮%f}/(main|viins)/❯%f} '
function zle-line-init zle-keymap-select {
  zle reset-prompt
}
zle -N zle-line-init
zle -N zle-keymap-select

export SHELL=$(which zsh)
